# -*- coding: utf-8 -*-
"""reward_policy_test.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YFKvW597ltfRpdiaubRmXg9Jy_mWkPfF
"""

"""

Reward Policy

Formula used:
r = completion_ratio - lambda * 1[skip < k]

Where:
- completion_ratio = play_time / duration
- 1[skip < k] is an indicator function: 1 if track was skipped before time k, 0 otherwise.
"""
from typing import Dict, Any
import numpy as np

EARLY_SKIP_THRESHOLD_MS = 30000  # 30 seconds

# lambda: Penalty weight for an early skip.
EARLY_SKIP_PENALTY_LAMBDA = 0.5


def calculate_reward(
    track_duration_ms: float,
    play_time_ms: float,
    is_skipped: bool,
    skip_latency_ms: float = None,
) -> float:
    """
    Calculates the reward for a single track play session based on play duration and skip behavior.

    Args:
        track_duration_ms: The total duration of the track in milliseconds.
        play_time_ms: The total time the user listened to the track in milliseconds.
        is_skipped: Boolean indicating if the track was explicitly skipped.
        skip_latency_ms: The time (in ms) at which the track was skipped.
                         Falls back to play_time_ms if not provided.

    Returns:
        A reward score.
    """

    if track_duration_ms <= 0:
        return 0.0

    # 1. Calculate the completion ratio (Play Fraction)
    completion_ratio = min(1.0, play_time_ms / track_duration_ms)

    # 2. Determine the skip penalty
    penalty = 0.0
    if is_skipped:
        latency = skip_latency_ms if skip_latency_ms is not None else play_time_ms

        if latency < EARLY_SKIP_THRESHOLD_MS:
            penalty = EARLY_SKIP_PENALTY_LAMBDA

    final_reward = completion_ratio - penalty

    return final_reward


# --- Testing ---

def test_reward_policy():
    print(f" Testing Reward Policy (Early Skip Threshold: {EARLY_SKIP_THRESHOLD_MS/1000}s, Penalty: {EARLY_SKIP_PENALTY_LAMBDA}) ")

    DURATION_3MIN = 180000.0

    # Case 1: Full listen (no skip)
    reward_1 = calculate_reward(DURATION_3MIN, DURATION_3MIN, is_skipped=False)
    print(f"Case 1 (Full Listen, 100%): Reward = {reward_1} (Expected: 1.0)")

    # Case 2: Early skip (listened 5s = 5000ms)
    play_time_2 = 5000.0
    reward_2 = calculate_reward(DURATION_3MIN, play_time_2, is_skipped=True, skip_latency_ms=play_time_2)
    expected_2 = (play_time_2 / DURATION_3MIN) - EARLY_SKIP_PENALTY_LAMBDA
    print(f"Case 2 (Early Skip, 5s): Reward = {reward_2:.4f} (Expected: {expected_2:.4f}, approx -0.4722)")

    # Case 3: Late skip
    play_time_3 = 60000.0
    reward_3 = calculate_reward(DURATION_3MIN, play_time_3, is_skipped=True, skip_latency_ms=play_time_3)
    expected_3 = (play_time_3 / DURATION_3MIN) # Completion Ratio, no penalty
    print(f"Case 3 (Late Skip, 60s): Reward = {reward_3:.4f} (Expected: {expected_3:.4f}, approx 0.3333)")


    play_time_4 = DURATION_3MIN / 2
    reward_4 = calculate_reward(DURATION_3MIN, play_time_4, is_skipped=False)
    expected_4 = 0.5
    print(f"Case 4 (Half Listen, No Skip): Reward = {reward_4:.4f} (Expected: {expected_4:.4f})")

if __name__ == '__main__':
    test_reward_policy()